esphome:
  friendly_name: RGB L1

# Configure API, OTA, Wi-Fi and captive portal as needed
api:
ota:
wifi:
captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/eerootsus/l1-esphome
      ref: main
    components: [ sonoff_l1 ]

esp8266:
  board: esp8285
  restore_from_flash: true

# UART logging needs to be disabled to be able to listen to the serial port, API logger is still available
logger:
  baud_rate: 0

uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 19200

light:
  - platform: sonoff_l1
    name: "Sonoff L1 LED Strip"
    restore_mode: RESTORE_DEFAULT_ON
    gamma_correct: 0.0
    default_transition_length: 1s
